language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpspec run --format=pretty -vvv
  - vendor/bin/php-cs-fixer fix --dry-run --diff
